#!/usr/bin/env bash

# This function just gets a specific aur package and installs it
# Files are in the tmp folder so cleaned up after reboot
function aurinst {
	echo Installing aur package $1
	if [ ! -d /tmp/aur ]; then
	    mkdir /tmp/aur
	fi
	if [ -d /tmp/aur/$1 ]; then
		rm -rf /tmp/aur/$1
	fi
	cd /tmp/aur && git clone https://aur.archlinux.org/$1.git && cd $1 && yes | makepkg -sic --needed
	rm -rf /tmp/aur/$1
}

sudo pacman -S --noconfirm --needed reflector rsync git
sudo systemctl enable --now reflector
sudo reflector --country gb --fastest 10 --threads 10 --save /etc/pacman.d/mirrorlist
sudo pacman -Sy --noconfirm

# Set Timezone
sudo ln -sf /usr/share/zoneinfo/Europe/London /etc/localtime

sudo pacman -Suy
sudo pacman -S --noconfirm --needed power-profiles-daemon bluez bluez-utils blueman acpi_call linux-headers acpid fwupd mesa libva-mesa-driver mesa-vdpau vulkan-mesa-layers vulkan-intel vulkan-radeon fprintd intltool xdg-utils dbus brightnessctl ca-certificates jq dmidecode 

sudo pacman -S --noconfirm --needed wpa_supplicant dnsmasq openresolv nss-mdns wireguard-tools ufw openvpn networkmanager-openvpn openssh libxcrypt-compat samba dnsutils nfs-utils modemmanager avahi wireguard-tools reflector openssh fastfetch btop rsync curl wget cups cups-pdf flatpak modemmanager modem-manager-gui

sudo systemctl enable --now cups.socket

# Add rule for printing by users
sudo touch /etc/polkit-1/rules.d/49-allow-passwordless-printer-admin.rules
sudo bash -c 'cat << EOF > /etc/polkit-1/rules.d/49-allow-passwordless-printer-admin.rules
polkit.addRule(function(action, subject) {
    if (action.id == "org.opensuse.cupspkhelper.mechanism.all-edit" &&
        subject.isInGroup("wheel")){
        return polkit.Result.YES;
    }
});
EOF'

# install yay
if [ ! -f /sbin/yay ]; then
	aurinst yay
fi

# Fix mdns printing
sudo sed -i 's/hosts\:\ mymachines\ resolve\ \[\!UNAVAIL\=return\]\ files\ myhostname\ dns/hosts: mymachines mdns [NOTFOUND=return] resolve [!UNAVAIL=return] files myhostname dns/g' /etc/nsswitch.conf


sudo sed -i 's/\#Experimental\ \=\ false/Experimental\ =\ true/g' /etc/bluetooth/main.conf
sudo systemctl enable --now bluetooth
sudo pacman -S --noconfirm --needed pipewire pipewire-audio pipewire-pulse pipewire-jack pavucontrol wireplumber

# Install Fonts
sudo pacman -S --noconfirm --needed ttf-ibm-plex ttf-liberation ttf-dejavu noto-fonts noto-fonts-extra noto-fonts-emoji ttf-carlito ttf-croscore ttf-hack ttf-anonymous-pro ttf-droid ttf-fira-code ttf-fira-mono ttf-fira-sans ttf-font-awesome ttf-jetbrains-mono ttf-opensans ttf-roboto ttf-roboto-mono nerd-fonts otf-font-awesome

# Install Hyprland
sudo pacman -S --needed --noconfirm ly gtk3 hyprland hyprlock hyprpolkitagent hypridle hyprpaper slurp grim swappy rofi-wayland rofi-calc rofi-emoji waybar thunar thunar-volman thunar-archive-plugin thunar-shares-plugin thunar-vcs-plugin xdg-desktop-portal-hyprland xdg-desktop-portal-gtk wl-clipboard feh nwg-look swaync swayosd pop-gtk-theme gvfs gvfs-nfs gvfs-smb sshfs wf-recorder wtype

sudo systemctl enable ly

# Install Apps
sudo pacman -S --needed --noconfirm cmus libreoffice mpv mc evince firefox thunderbird git tig neovim less go gopls cmake gettext nodejs npm ghostty
yay -S --noconfirm --needed google-chrome sublime-text-4 google-cloud-cli

sudo flatpak install -y flathub \
	spotify \
	slack \
	com.valvesoftware.Steam \
	im.riot.Riot \
	org.telegram.desktop \
	org.telegram.desktop.webview \
	com.bitwarden.desktop \
	app/com.usebruno.Bruno/x86_64/stable \
	app/io.beekeeperstudio.Studio/x86_64/stable
