#!/usr/bin/env bash

echo "Which disk should I use?"
read DISK

echo "What is the name of the computer?"
read COMPNAME

echo "Root password: "
read ROOTPASSWORD

echo "Username of the user: "
read USERNAME

echo "Password of the user: "
read USERPASSWORD

echo $DISK
echo $COMPNAME

pacman-key --init
pacman-key --populate arch-linux
pacman -Sy --noconfirm archlinux-keyring

timedatectl set-ntp true

parted /dev/vda mklabel gpt \
	mkpart ESP fat32 1Mib 512Mib \
	mkpart BOOT ext4 512Mib 1024Mib \
	mkpart ROOT ext4 1GiB 100% --script

parted /dev/vda set 1 esp on --script

mkfs.ext4 -L root /dev/vda3
mkfs.ext4 -L boot /dev/vda2
mkfs.vfat -n "EFI SYSTEM" /dev/vda1

mount /dev/vda3 /mnt
mkdir /mnt/boot
mount /dev/vda2 /mnt/boot
mkdir /mnt/boot/efi
mount /dev/vda1 /mnt/boot/efi

dd if=/dev/zero of=/mnt/swap bs=1M count=4096
chmod 0600 /mnt/swap
mkswap /mnt/swap
swapon /mnt/swap

pacstrap -i /mnt base base-devel linux linux-firmware networkmanager efibootmgr grub sudo vi vim bash bash-completion
genfstab -U /mnt >> /mnt/etc/fstab

echo $COMPNAME >> /mnt/etc/hostname

echo '127.0.0.1 localhost' >> /mnt/etc/hosts
echo '::1 localhost' >> /mnt/etc/hosts
echo 127.0.1.1 $COMPNAME.net.bowers1.com $COMPNAME >> /mnt/etc/hosts

echo 'LANG=en_US.UTF8' >> /mnt/etc/locale.conf 
echo 'KEYMAP=us' >> /mnt/etc/vconsole.conf
echo 'en_GB.UTF-8 UTF-8' >> /mnt/etc/locale.gen
echo 'en_US.UTF-8 UTF-8' >> /mnt/etc/locale.gen

arch-chroot /mnt locale-gen
arch-chroot /mnt mkinitcpio -p linux
arch-chroot /mnt grub-install --boot-directory=/boot --efi-directory=/boot/efi /dev/nvme0n1p2
arch-chroot /mnt grub-mkconfig -o /boot/grub/grub.cfg
arch-chroot /mnt grub-mkconfig -o /boot/efi/EFI/arch/grub.cfg

arch-chroot /mnt useradd -m $USERNAME -G wheel,audio,video
arch-chroot /mnt echo root:$ROOTPASSWORD | chpasswd

curl -k https://raw.githubusercontent.com/garybowers/comp-setup/main/setup-arch -o /mnt/setup-arch
chmod +x /mnt/setup-arch

