#!/usr/bin/env bash

echo "Which disk should I use?"
read DISK

echo "What is the name of the computer?"
read COMPNAME

echo "Root password: "
read ROOTPASSWORD

echo "Username of the user: "
read UNAME

echo "Password of the user: "
read UPASSWORD

echo $DISK
echo $COMPNAME

pacman-key --init
pacman-key --populate arch-linux
pacman -Sy --noconfirm archlinux-keyring

timedatectl set-ntp true

parted /dev/vda mklabel gpt \
	mkpart ESP fat32 1Mib 512Mib \
	mkpart BOOT ext4 512Mib 1024Mib \
	mkpart ROOT ext4 1GiB 100% --script

parted /dev/vda set 1 esp on --script

mkfs.ext4 -L root /dev/vda3
mkfs.ext4 -L boot /dev/vda2
mkfs.vfat -n "EFI SYSTEM" /dev/vda1

mount /dev/vda3 /mnt
mkdir /mnt/boot
mount /dev/vda2 /mnt/boot
mkdir /mnt/boot/efi
mount /dev/vda1 /mnt/boot/efi

dd if=/dev/zero of=/mnt/swap bs=1M count=4096
chmod 0600 /mnt/swap
mkswap /mnt/swap
swapon /mnt/swap

pacstrap -i /mnt base base-devel linux linux-firmware networkmanager efibootmgr grub sudo vi vim bash bash-completion
genfstab -U /mnt >> /mnt/etc/fstab

echo $COMPNAME >> /mnt/etc/hostname

echo '127.0.0.1 localhost' >> /mnt/etc/hosts
echo '::1 localhost' >> /mnt/etc/hosts
echo 127.0.1.1 $COMPNAME.net.bowers1.com $COMPNAME >> /mnt/etc/hosts

echo 'LANG=en_US.UTF8' >> /mnt/etc/locale.conf 
echo 'KEYMAP=us' >> /mnt/etc/vconsole.conf
echo 'en_GB.UTF-8 UTF-8' >> /mnt/etc/locale.gen
echo 'en_US.UTF-8 UTF-8' >> /mnt/etc/locale.gen

arch-chroot /mnt locale-gen
arch-chroot /mnt mkinitcpio -p linux
arch-chroot /mnt grub-install --boot-directory=/boot --efi-directory=/boot/efi /dev/nvme0n1p2
arch-chroot /mnt grub-mkconfig -o /boot/grub/grub.cfg
arch-chroot /mnt grub-mkconfig -o /boot/efi/EFI/arch/grub.cfg

arch-chroot /mnt useradd -m $UNAME -G wheel,audio,video
arch-chroot /mnt echo $UNAME:$UPASSWORD | chpasswd
arch-chroot /mnt echo $UNAME:$UPASSWORD

arch-chroot /mnt echo root:$ROOTPASSWORD | chpasswd
arch-chroot /mnt echo root:$ROOTPASSWORD

curl -k https://raw.githubusercontent.com/garybowers/comp-setup/main/setup-arch -o /mnt/setup-arch
chmod +x /mnt/setup-arch


# Install Network Stack
arch-chroot /mnt pacman -S --noconfirm --needed wpa_supplicant dnsmasq openresolv nss-mdns wireguard-tools ufw openvpn networkmanager-openvpn openssh libxcrypt-compat samba dnsutils

# Install Audio Stack
arch-chroot /mnt pacman -S --noconfirm --needed pavucontrol pipewire pipewire-pulse pipewire-jack pipewire-alsa

arch-chroot /mnt pacman -S --noconfirm --needed ttf-ibm-plex ttf-liberation ttf-dejavu xorg-fonts-misc xorg-fonts-type1 \
                                    noto-fonts noto-fonts-extra noto-fonts-emoji ttf-carlito ttf-croscore ttf-hack ttf-anonymous-pro \
                                    ttf-droid ttf-fira-code ttf-fira-mono ttf-fira-sans ttf-font-awesome ttf-jetbrains-mono \
                                    ttf-opensans ttf-roboto-mono ttf-roboto

arch-chroot /mnt pacman -S --noconfirm --needed firefox thunderbird libreoffice thunderbird gimp keepassxc

arch-chroot /mnt pacman -S --noconfirm --needed gdm gnome-shell gnome-backgrounds gnome-color-manager gnome-disk-utility gnome-font-viewer gnome-menus \
                                      gnome-remote-desktop gnome-screenshot gnome-shell-extensions gnome-software gnome-system-monitor gnome-connections \
                                      gnome-user-share mutter nautilus orca xdg-user-dirs-gtk simple-scan gnome-calculator gnome-contacts rhythmbox \
                                      gnome-themes-extra gnome-shell-extension-appindicator gnome-tweaks gnome-calendar deja-dup gnome-terminal \
                                      system-config-printer modemmanager nautilus-image-converter nautilus-sendto nautilus-share gnome-shell-extension-gtile \
                                      gnome-icon-theme-extras dconf-editor eog remmina libsass parallel sassc gtk-engine-murrine fd gedit gstreamer gst-libav \
                                      gnome-mahjongg gnome-weather obsidian-icon-theme papirus-icon-theme

arch-chroot /mnt systemctl enable gdm


reboot